window.NAMORO = {
  ele: "Bruno",
  ela: "Maria Luisa",
  inicio: "2025-10-02T00:00:00-03:00",

  musica: "assets/musica/3x4.mp3",

  subtitulo: "Um ano de nós, e ainda é só o primeiro capítulo.",

  capa: ["festa-abraco", "igreja", "van-gogh", "filme", "festa-luzes", "festa-beijo"],

  fotos: {
    "festa-abraco": { legenda: "Fotinha na cabine", alt: "Bruno e Maria Luisa abraçados em uma festa à noite, ela de vestido azul", w: 1200, h: 1600, pos: "50% 45%" },
    "igreja":       { legenda: "De azul, a mais linda", alt: "Os dois de mãos dadas no corredor de uma igreja enfeitada com flores brancas", w: 1200, h: 1600, pos: "50% 50%" },
    "festa-luzes":  { legenda: "Casamento P&M", alt: "Os dois sob luminárias de palha e flores lilás em uma festa", w: 1200, h: 1548, pos: "50% 45%" },
    "cabine":       { legenda: "Fotinhas na cabine", alt: "Tirinha de cabine de fotos com quatro poses dos dois", w: 1200, h: 1600, pos: "50% 50%" },
    "festa-beijo":  { legenda: "Fotinha na cabine", alt: "Bruno dando um beijo na bochecha da Maria Luisa, que sorri de olhos fechados", w: 960, h: 1280, pos: "50% 40%" },
    "natal-luzes":  { legenda: "Primeiro época de natal juntos", alt: "Selfie dos dois em frente a um túnel de luzes de Natal", w: 1200, h: 1600, pos: "50% 40%" },
    "arvore-natal": { legenda: "Natal em CG", alt: "Os dois se olhando em frente a uma árvore de Natal gigante de luzes douradas", w: 1200, h: 1600, pos: "50% 70%" },
    "carnaval":     { legenda: "Bloco de dois", alt: "Selfie dos dois sorrindo com abadás coloridos de carnaval", w: 900, h: 1600, pos: "50% 30%" },
    "show-beijo":   { legenda: "No meio da multidão, só você", alt: "Bruno beijando a bochecha da Maria Luisa em um show", w: 1200, h: 1600, pos: "50% 45%" },
    "van-gogh":     { legenda: "Dentro de um quadro", alt: "Os dois de costas em uma exposição imersiva com amendoeiras em flor", w: 1200, h: 1600, pos: "50% 50%" },
    "filme":        { legenda: "Em filme, do jeitinho que foi", alt: "Foto analógica dos dois rindo abraçados", w: 1067, h: 1600, pos: "50% 40%" },
    "por-do-sol":   { legenda: "No dia do pedido", alt: "Selfie dos dois em frente a um lago no pôr do sol", w: 1600, h: 900, pos: "42% 60%" },
    "ceu-azul":     { legenda: "No nosso dia 02", alt: "Selfie dos dois com o céu azul ao fundo, ela com a cabeça no ombro dele", w: 900, h: 1600, pos: "50% 30%" },
    "cenario":      { legenda: "No PP", alt: "Os dois em frente a uma fachada amarela com portas vermelhas", w: 1200, h: 1600, pos: "50% 45%" },
    "academia":     { legenda: "Metendo um treinão", alt: "Selfie no espelho da academia", w: 1200, h: 1600, pos: "35% 55%" },
    "sofa":         { legenda: "Assistindo filme", alt: "Selfie dos dois deitados, sorrindo", w: 1600, h: 1200, pos: "62% 45%" },
    "sorriso":      { legenda: "Meu sorriso favorito", alt: "Selfie dos dois bem sorridentes em casa", w: 1600, h: 1200, pos: "55% 40%" },
    "beijinho":     { legenda: "Linda demais mininu", alt: "Bruno beijando a bochecha da Maria Luisa em casa", w: 900, h: 1600, pos: "45% 40%" },
    "careta":       { legenda: "KKKKKKKKKK", alt: "Os dois fazendo careta com a língua para fora", w: 1600, h: 1200, pos: "55% 40%" },
    "outubro-1":    { legenda: "De passeio no Imagineland", alt: "Os dois em um evento ao lado de uma pessoa fantasiada de Hollow Knight", w: 960, h: 1280, pos: "40% 55%" },
    "outubro-2":    { legenda: "Esperando um bistrozinho", alt: "Selfie dos dois sorrindo em frente a uma parede cinza", w: 720, h: 1280, pos: "50% 40%" },
    "novembro-1":   { legenda: "Apreciando o por do sol no balde S2", alt: "Selfie dos dois dentro do carro à noite", w: 960, h: 1280, pos: "50% 45%" },
    "novembro-2":   { legenda: "Torcendo loucamente pela Facisa", alt: "Selfie dos dois na arquibancada de um ginásio", w: 1600, h: 900, pos: "45% 50%" },
    "novembro-3":   { legenda: "Fazendo os gostos de junim", alt: "Selfie dos dois passeando com um cachorro à noite", w: 1200, h: 1600, pos: "50% 50%" },
    "janeiro-1":    { legenda: "Esperando pra comer um hamburguer superfaturado", alt: "Selfie dos dois sorrindo em um bar à meia-luz", w: 1600, h: 1200, pos: "50% 40%" },
    "janeiro-2":    { legenda: "Diretamente de Hogwarts", alt: "Os dois com cachecóis de Hogwarts em um cenário de Harry Potter", w: 1600, h: 1200, pos: "50% 45%" },
    "marco-1":      { legenda: "Fofinnnns", alt: "Selfie dos dois, ela apertando a bochecha dele", w: 1200, h: 1600, pos: "50% 65%" },
    "julho-1":      { legenda: "Colocando expectativa na seleção", alt: "Os dois com camisa e cachecol do Brasil", w: 960, h: 1280, pos: "50% 55%" },
    "agosto-1":     { legenda: "fim de tarde a dois", alt: "Selfie dos dois abraçados ao entardecer", w: 960, h: 1280, pos: "50% 45%" },
    "agosto-2":     { legenda: "S2", alt: "Os dois fazendo careta com a língua para fora ao entardecer", w: 960, h: 1280, pos: "50% 50%" },
  },

  meses: [
    { mes: "Outubro",   ano: 2025, titulo: "Nosso primeiro mês",      texto: "Do mês que mais fiquei nervoso, nossa primeira foto namorando, logo após o pedido e nosso primeiro evento nerd", fotos: ["por-do-sol", "ceu-azul", "outubro-1", "outubro-2"] },
    { mes: "Novembro",  ano: 2025, titulo: "Conhecendo você",     texto: "Das nossas visitas ao balde, primeira partida de basquete e passeio com Juninho", fotos: ["novembro-1", "novembro-2", "novembro-3"] },
    { mes: "Dezembro",  ano: 2025, titulo: "Nosso primeiro Natal", texto: "Primeiro natal juntos e no mesmo mês, o casamento de Pedro e Marialice", fotos: ["natal-luzes", "igreja", "festa-luzes", "festa-beijo", "festa-abraco", "cabine"] },
    { mes: "Janeiro",   ano: 2026, titulo: "De Janeiro a Janeiro",   texto: "Nosso primeiro ano novo e viagem namorando", fotos: ["van-gogh", "arvore-natal", "janeiro-1", "janeiro-2"] },
    { mes: "Fevereiro", ano: 2026, titulo: "Bloco de dois",        texto: "Carnaval juntos no sitio da sua familia e uma fotinha no sofá da sua casa", fotos: ["carnaval", "sofa"] },
    { mes: "Março",     ano: 2026, titulo: "Rindo à toa",          texto: "Das vezes em que você veio aqui em casa e nosso treinão", fotos: ["sorriso", "careta", "marco-1", "academia"] },
    { mes: "Abril",     ano: 2026, titulo: "Love drive",           texto: "Esse mês não tiramos fotos juntos, mas vou colocar um video do dia 2 de março", fotos: [], video: "assets/fotos/video/abril-1.mp4", videoLegenda: "arriscando a vida com meu amor kkkkkkkkk dirigiu bem direitinho ☝️" },
    { mes: "Maio",      ano: 2026, titulo: "No meio da multidão",  texto: "Nosso segundo show juntos de Engenheiros do Hawai, quase 1 ano depois de termos ido o primeiro, ainda sem namorar", fotos: ["show-beijo"] },
    { mes: "Junho",     ano: 2026, titulo: "Arraiá do amor",       texto: "Nosso primeiro e único dia de PP desse ano", fotos: ["cenario"] },
    { mes: "Julho",     ano: 2026, titulo: "Dale Brasil",       texto: "Torcendo pelo Brasil no primeiro jogo da seleção na copa", fotos: ["julho-1"] },
    { mes: "Agosto",    ano: 2026, titulo: "Cada vez mais nós",    texto: "Aqui a gente tava só aproveitando o por do sol mais foda que tem, ao lado de quem amo", fotos: ["agosto-1", "agosto-2"] },
    { mes: "Setembro",  ano: 2026, titulo: "Quase um ano",         texto: "Aqui foi nossa comemoração de 11 meses de namoro, indo ao cinema e depois no gameStation, assim como a gente gosta", fotos: [], video: "assets/fotos/video/setembro-1.mp4", videoLegenda: "quase um ano" },
  ],

  carta: [
    "Há um ano atrás eu não fazia noção do rumo que a minha vida tomaria, do brilho que você traria a ela e do quão importante uma pessoa pode se tornar na nossa vida.",
    "Nesse ultimo ano eu fui o homem mais feliz do mundo, por de fato te conhecer de verdade e por ver a vida sendo seu namorado, foi a minha melhor decisão.",
    "Obrigado por cada risada, cada conversa, cada abraço apertado e por transformar os dias mais comuns nos meus preferidos. Hoje eu sou como a musica do Nando Reis, esperando que o tempo voe, que a semana acabe, pra poder estar de volta ao seu lado, pois você hoje é o meu lar. ",
    "Se eu pudesse voltar no tempo, escolheria você de novo em cada mês dessa linha do tempo. E vou continuar escolhendo em todos os que ainda vêm.",
    "Feliz 1 ano, meu amor. Eu te amo.",
  ],

  final: "Eu te amo, Maria Luisa. Hoje, amanhã e em todos os próximos capítulos.",
};
